# robot_base_frame : BODY
# footprint: [[-0.25, -0.4], [-0.25, 0.4], [1.25, 0.4], [1.25, -0.4]]
# robot_base_frame : cart_center
footprint: [[-1.35, -0.4], [-1.35, 0.4], [0.15, 0.4], [0.15, -0.4]]
footprint_padding: 0.01

# robot_base_frame: BODY
robot_base_frame: cart_center
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#pointcloud definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_pointcloud:
    observation_sources: pointcloud
    pointcloud: {data_type: PointCloud2, min_obstacle_height: 0.15, max_obstacle_height: 2.0, clearing: true, marking: true, topic: filter_cart_pointcloud/output, inf_is_valid: true}

inflation:
    inflation_radius: 1.0
