# global_frame: odom
global_frame: map
# global_frame: biped_odom_particle
rolling_window: true

plugins:
  - {name: obstacles_pointcloud, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,            type: "costmap_2d::InflationLayer"}
  - {name: gradient,             type: "object_navigation_layers::GradientLayer",  base_class_type: "costmap_2d::Layer"}
  - {name: grad_inflation,       type: "costmap_2d::InflationLayer"}
  - {name: object,               type: "object_navigation_layers::ObjectLayer",  base_class_type: "costmap_2d::Layer"}
