# robot_base_frame : BODY
# footprint: [[-0.25, -0.4], [-0.25, 0.4], [1.25, 0.4], [1.25, -0.4]]
# footprint_padding: 0.01
# robot_base_frame : cart_center (0.5m)
# footprint: [[-0.75, -0.4], [-0.75, 0.4], [0.75, 0.4], [0.75, -0.4]]
# robot_base_frame : cart_center (1.1m)
# footprint: [[-1.35, -0.35], [-1.35, 0.35], [0.15, 0.35], [0.15, -0.35]]
# robot_base_frame : cart_center (1.45m)
footprint: [[-1.7, -0.35], [-1.7, 0.35], [0.0, 0.35], [0.0, -0.35]]
footprint_padding: 0.01

# robot_base_frame: BODY
robot_base_frame: cart_center
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#pointcloud definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_pointcloud:
    observation_sources: pointcloud
    pointcloud: {data_type: PointCloud2, min_obstacle_height: 0.3, max_obstacle_height: 2.0, clearing: true, marking: true, topic: accumulated_heightmap_pointcloud/output, inf_is_valid: true}

inflation:
    cost_scaling_factor: 10.0
    inflation_radius: 1.0
    use_custom_inscribed_radius: false

grad_inflation:
    cost_scaling_factor: 5.0
    inflation_radius: 2.0
    use_custom_inscribed_radius: true
    custom_inscribed_radius: 0.3
